name: CI Cache Demo (npm)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  cache-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Locate npm cache dir
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> "$GITHUB_OUTPUT"

      - name: Cache npm
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: cache-5f86865
          restore-keys: |
            cache-5f86865

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          elif [ -f package.json ]; then
            npm install
          else
            echo "No package.json found; skipping npm install."
          fi

      - name: prime-cache-5f86865
        run: echo "cache_hit=${{ steps.cache.outputs['cache-hit'] }}"
